"""add status cols to sources

Revision ID: 798edbedad35
Revises: e653495e3ea2
Create Date: 2025-10-16 12:09:09.199779

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '798edbedad35'
down_revision: Union[str, Sequence[str], None] = 'bdae921efe47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('raw_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_articles_raw_fetched_at'), 'articles_raw', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_articles_raw_raw_id'), 'articles_raw', ['raw_id'], unique=False)
    op.create_index(op.f('ix_articles_raw_source_id'), 'articles_raw', ['source_id'], unique=False)
    op.create_index(op.f('ix_articles_raw_url'), 'articles_raw', ['url'], unique=False)
    op.drop_index(op.f('ix_raw_articles_fetched_at'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_raw_id'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_source_id'), table_name='raw_articles')
    op.drop_index(op.f('ix_raw_articles_url'), table_name='raw_articles')
    op.drop_table('raw_articles')
    op.add_column('sources', sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('sources', sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_sources_created_at'), table_name='sources')
    op.drop_index(op.f('ix_sources_last_run_at'), table_name='sources')
    op.drop_index(op.f('ix_sources_updated_at'), table_name='sources')
    op.drop_column('sources', 'timeout_sec')
    op.drop_column('sources', 'notes')
    op.drop_column('sources', 'max_retries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', sa.Column('max_retries', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('sources', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sources', sa.Column('timeout_sec', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_sources_updated_at'), 'sources', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sources_last_run_at'), 'sources', ['last_run_at'], unique=False)
    op.create_index(op.f('ix_sources_created_at'), 'sources', ['created_at'], unique=False)
    op.drop_column('sources', 'last_error')
    op.drop_column('sources', 'last_status')
    op.create_table('raw_articles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('raw_articles_source_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('raw_articles_pkey'))
    )
    op.create_index(op.f('ix_raw_articles_url'), 'raw_articles', ['url'], unique=False)
    op.create_index(op.f('ix_raw_articles_source_id'), 'raw_articles', ['source_id'], unique=False)
    op.create_index(op.f('ix_raw_articles_raw_id'), 'raw_articles', ['raw_id'], unique=False)
    op.create_index(op.f('ix_raw_articles_fetched_at'), 'raw_articles', ['fetched_at'], unique=False)
    op.drop_index(op.f('ix_articles_raw_url'), table_name='articles_raw')
    op.drop_index(op.f('ix_articles_raw_source_id'), table_name='articles_raw')
    op.drop_index(op.f('ix_articles_raw_raw_id'), table_name='articles_raw')
    op.drop_index(op.f('ix_articles_raw_fetched_at'), table_name='articles_raw')
    op.drop_table('articles_raw')
    # ### end Alembic commands ###
