"""add sources

Revision ID: 9c1a7ad9504e
Revises:
Create Date: 2025-10-15 21:31:35.535539

"""

import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9c1a7ad9504e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("feed_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("kind", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("cadence_minutes", sa.Integer(), nullable=False),
        sa.Column("timeout_sec", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_created_at"), "source", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_source_last_run_at"), "source", ["last_run_at"], unique=False
    )
    op.create_index(op.f("ix_source_slug"), "source", ["slug"], unique=True)
    op.create_index(
        op.f("ix_source_updated_at"), "source", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_updated_at"), table_name="source")
    op.drop_index(op.f("ix_source_slug"), table_name="source")
    op.drop_index(op.f("ix_source_last_run_at"), table_name="source")
    op.drop_index(op.f("ix_source_created_at"), table_name="source")
    op.drop_table("source")
    # ### end Alembic commands ###
